services:
  proyecto:
    image: proyecto:latest
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/proyectospring
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db



  db:
    image: sql:latest
    container_name: productos-contenedor
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: proyectospring
      
  frontend:
    image: frontend:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - proyecto
    ports:
      - "80:80"
    networks:
      - conection

networks:
  conection:
    driver: bridge
